stages:
  - compile
  - test
build:
  stage: compile
  image: golang:1.13
  script:
    - go get -d -v
    - go build -o bin/golang-gin-poc -v .
test:
  stage: test
  script:
    - go test service/*.go